package com.example.zer.weiyingdemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zer.weiyingdemo.model.bean.LishiBean;
import com.example.zer.weiyingdemo.model.bean.ShouCangBean;

import com.example.zer.weiyingdemo.db.LishiBeanDao;
import com.example.zer.weiyingdemo.db.ShouCangBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lishiBeanDaoConfig;
    private final DaoConfig shouCangBeanDaoConfig;

    private final LishiBeanDao lishiBeanDao;
    private final ShouCangBeanDao shouCangBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lishiBeanDaoConfig = daoConfigMap.get(LishiBeanDao.class).clone();
        lishiBeanDaoConfig.initIdentityScope(type);

        shouCangBeanDaoConfig = daoConfigMap.get(ShouCangBeanDao.class).clone();
        shouCangBeanDaoConfig.initIdentityScope(type);

        lishiBeanDao = new LishiBeanDao(lishiBeanDaoConfig, this);
        shouCangBeanDao = new ShouCangBeanDao(shouCangBeanDaoConfig, this);

        registerDao(LishiBean.class, lishiBeanDao);
        registerDao(ShouCangBean.class, shouCangBeanDao);
    }
    
    public void clear() {
        lishiBeanDaoConfig.clearIdentityScope();
        shouCangBeanDaoConfig.clearIdentityScope();
    }

    public LishiBeanDao getLishiBeanDao() {
        return lishiBeanDao;
    }

    public ShouCangBeanDao getShouCangBeanDao() {
        return shouCangBeanDao;
    }

}
